# Generated by Django 4.1.5 on 2023-01-29 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="items",),
        migrations.RemoveField(model_name="order", name="user",),
        migrations.RemoveField(model_name="orderitem", name="item",),
        migrations.DeleteModel(name="Item",),
        migrations.DeleteModel(name="Order",),
        migrations.DeleteModel(name="OrderItem",),
    ]
