# Generated by Django 4.1.5 on 2023-01-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_item_image_item_inventory_order_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(
                blank=True, default="", null=True, upload_to="images"
            ),
        ),
    ]
