# Generated by Django 4.1.5 on 2023-01-30 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0006_rename_image_item_item_img_remove_orderitem_image_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem", old_name="images", new_name="img",
        ),
    ]
