# Generated by Django 4.1.5 on 2023-01-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_alter_item_item_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_img",
            field=models.ImageField(
                blank=True, default="", null=True, upload_to="images"
            ),
        ),
    ]
